config/routes.rb
Rails.application.routes.draw do





  root 'static_pages#home'

  get     '/home',            to: 'static_pages#home'
  get     '/instrucciones',   to: 'static_pages#instrucciones'
  get     '/resultados',      to: 'static_pages#resultados'
  get     '/contacto',        to: 'static_pages#contacto'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  get     '/stats',           to: 'stats#create'  #personalizada



  resources :stats, only: [:create, :show] do
    resources :stat_steps, only: [:edit, :update]
  end

  #lo de arriba permite=>  stats/:stat_id/stat_parts/:id/edit

  resources :stats

  resources :places do
    resources :commons, :users
  end

  resources :users #hay disonancia de que esta línea tenga que existir

  resources :commons #no deja de ser necesaria la declaración de estas rutas.
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/user.rb
class User < ApplicationRecord
  has_many :shares
  has_many :commons, through: :shares
  belongs_to :place
  has_one :stat
  # #
  # VALID_DEPTO_REGEX = /\A[a-zA-Z\d]{3,7}\z/
  # validates :depto, presence: true, length: { maximum: 5}, format: { with: VALID_DEPTO_REGEX },
  #                   uniqueness: { case_sensitive: false}
  # validates :condo, presence: true, length: { maximum: 10}
  has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }

end

#prueba para commiteog

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user, only: [:new, :index, :edit, :update, :destroy] # »»» los 'users' también deben poder 'update', 'edit'«««
  before_action :set_user, only:	[:show,	:edit,	:update,	:destroy]
  #before_action :set_place

  def index #este método vamos a excluirlo eventualmente
    # @places = Place.find(params[:place_id])
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @place = Place.find(params[:place_id])
    @user = User.new #ajustado para la nueva asociación con 'Place'
  end

  def create
    puts "»»»»" * 20
    @place = Place.find(params[:place_id])
    @user = @place.users.build(user_params) #actualizado para la asociación con 'Place'
   if @user.save
     flash[:success] = "Participante registrado"
     redirect_to @user
   else
     render 'new'
   end
 end

 def edit
   @user = User.find(params[:id])
 end

 def update
   @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "Participante actualizado"
     redirect_to @user
   else
     render 'edit'
   end
 end

 def destroy
   User.find(params[:id]).destroy
   flash[:success] = "User deleted"
   redirect_to @place #«««««««FIX_IT!!! but_fine_my_friend!»»»»»»»
 end

    private
      def set_place
        @place = Place.find(params[:place_id])
      end

      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:condo, :depto, :password, # »»» agregar el 'account_attr' a los user_params «««
                                     :password_confirmation, :account, :place_id)
      end

      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@place, @user]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :departamento %>
      <%= f.text_field :depto, class: 'form-control' %>

      <%= f.label :condominio %>
      <%= f.text_field :condo, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear participante", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.depto + " " + user.condo, user %>

  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "edit",  edit_user_path(user.id) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "¿Seguro, carnal?" } %>

    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Editar participante") %>
<h1>Edita al participante</h1>

<%= render 'form'%>

app/views/users/index.html.erb
<!-- Esta vista no opera más, la buena es la que incluye places -->

<% provide(:title, 'Todos los participantes') %>
<h1>Participantes</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
    <br>
    <%= link_to "Agregar", new_place_user_path, class: "btn btn-primary" %>
</ul>


<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Registrar Usuarios</h1>

<%= render 'form' %>

<%=	link_to	'Back',	:back	%>

app/views/users/show.html.erb
<% provide(:title, @user.depto) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.depto + " " + @user.condo %>
      </h1>
    </section>
  </aside>
</div>